package com.project.v1.testing.recipesproject1.models

data class Recipe(
    val vegetarian: Boolean = false,
    val vegan: Boolean = false,
    val glutenFree: Boolean = false,
    val dairyFree: Boolean = false,
    val veryHealthy: Boolean = false,
    val cheap: Boolean = false,
    val veryPopular: Boolean = false,
    val sustainable: Boolean = false,
    val lowFodmap: Boolean = false,
    val weightWatcherSmartPoints: Long = 0L,
    val gaps: String = "",
    val preparationMinutes: Long = 0L,
    val cookingMinutes: Long = 0L,
    val aggregateLikes: Long = 0L,
    val healthScore: Long = 0L,
    val creditsText: String = "",
    val license: String = "",
    val sourceName: String = "",
    val pricePerServing: Double = 0.0,
    val extendedIngredients: List<ExtendedIngredient>? = null,
    val id: Long = 0L,
    val title: String = "",
    val readyInMinutes: Long = 0L,
    val servings: Long = 0L,
    val sourceUrl: String = "",
    val image: String = "",
    val imageType: String = "",
    val summary: String = "",
    val cuisines: List<String> = listOf(""),
    val dishTypes: List<String> = listOf(""),
    val diets: List<String> = listOf(""),
    val occasions: List<String> = listOf(""),
    val instructions: String = "",
    val analyzedInstructions: List<AnalyzedInstruction>? = null,
    val originalId: Any? = null,
    val spoonacularSourceUrl: String = "",
):java.io.Serializable